name: site
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:

  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  flutter_native_splash: ^2.1.6
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  provider: ^6.0.2

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: vazir
      fonts:
        - asset: assets/fonts/vazir_regular.ttf
        - asset: assets/fonts/vazir_medium.ttf
          weight: 600
        - asset: assets/fonts/vazir_bold.ttf
          weight: 700

